### ISSUE TITLE
Wont install on BandagedBD

### ISSUE THREAD

**Issue by NicciZar** [An00nymushun/DiscordFreeEmojis#13]
When Dragging the "DiscordFreeEmojis.user.js" into the Plugin directory "C:\Users\Nicci\AppData\Roaming\BetterDiscord\plugins"
BandagedBD wont recognize that a new Plugin has been added. I also tried restarten my Discord but it didnt help.

Am I doing something wrong here?

I am using
Stable 77645 (6bbb9a6)
BBD 0.3.5
Host 0.0.309
Injector 0.6.2
Windows 10 64-Bit (10.0.19042)

**Comment by NicciZar** [comment]
NVM I installed it with the PS1 Script.
Would be cool tho if it handles like a normal Discord plugin via the file.

**Comment by Orangian** [comment]
This works if you copy DiscordFreeEmojis.plugin.js to your folder.
