### ISSUE TITLE
Not working with Powercord.

### ISSUE THREAD

**Issue by BreadsRL** [An00nymushun/DiscordFreeEmojis#14]
Hey,

I have been using this plugin for a while with Powercord, using another plugin called "BDCompat" which helps BD plugins be compatible with Powercord. This Emoji plugin stopped working for me a few hours ago. I tried re-enabling but nothing worked. Any solutions?

Thanks.

**Comment by An00nymushun** [comment]
It should be fixed now

**Comment by BreadsRL** [comment]
Thank you so much.
