### ISSUE TITLE
Plugin has completely broken as of recent

### ISSUE THREAD

**Issue by ImperatorStorm** [An00nymushun/DiscordFreeEmojis#15]
Recently, the plugin has completely broken, causing the plugin to change all timestamps to chinese and fail to do its intended purpose.

**Comment by bill88t** [comment]
Yea, all the timestamps are Chinese now and the emojis don't work. Not even if you type them.

**Comment by An00nymushun** [comment]
There was a Discord change that made it break, it should work now

**Comment by Ashmitw** [comment]
The timestamp was fixed but emojis are still not working for me

**Comment by An00nymushun** [comment]
Did you update the plugin file and did you enable the plugin?
Which version are you using?

**Comment by Vyxxxx** [comment]
I'm still having both problems and im using the most updated version

**Comment by An00nymushun** [comment]
But which type, and what's the version number inside the file?

**Comment by bill88t** [comment]
I don't know about you guys, I just got the new version, enabled it and everything works as intended.

**Comment by Vyxxxx** [comment]
> But which type, and what's the version number inside the file?

So I installed it normally instead of using the installer and it worked, so turns out that was the problem. New ver works fine.

**Comment by Vyxxxx** [comment]
V1.3 That is. Thank you much!

**Comment by dan3401** [comment]
I had all of the same issues, better disocrd label it as out of date. an uninstall an reinstall fixed the issues and the warning

**Comment by dan3401** [comment]
I have all of the same issues but better discord is also giving a warning that the plugin is out of date (and a reinstall hasn't solved it)

**Comment by An00nymushun** [comment]
Check the version inside the file

**Comment by dan3401** [comment]
the version number is 1.3
![image](https://user-images.githubusercontent.com/13206890/111079724-235aba80-84f3-11eb-8b8a-631d3d632997.png)

**Comment by An00nymushun** [comment]
Check if you also have an old version in your plugins directory

**Comment by dan3401** [comment]
Nope only that version

**Comment by An00nymushun** [comment]
Maybe you have the installed version? Check %localappdata%

**Comment by luni3359** [comment]
I can confirm that it works now after drag-and-dropping the latest version to the plugins folder. To those looking what to do, you have to overwrite the old one with the latest.

**Comment by ImperatorStorm** [comment]
Closing as issue is fixed.
