### ISSUE TITLE
Language of Timestamp is Japanese if Plugin is enabled

### ISSUE THREAD

**Issue by FreshDoktor** [An00nymushun/DiscordFreeEmojis#16]
My language settings are set to German, if i enable your Plugin there are behind the messages " — 今天 12:52" instead of "heute 12:52". Everything else does have the right language.

With your Plugin:
![image](https://user-images.githubusercontent.com/39657947/111029146-4ace5c00-83fb-11eb-9a95-3628af9711e9.png)

If the Plugin is disabled: 
![image](https://user-images.githubusercontent.com/39657947/111029167-74878300-83fb-11eb-9f1e-a08b16cc6b53.png)

**Comment by ImperatorStorm** [comment]
see #15
