### ISSUE TITLE
Meta not found for 64px (or normal for that matter)

### ISSUE THREAD

**Issue by jryn** [An00nymushun/DiscordFreeEmojis#19]
Am I retarded or something?
![image](https://user-images.githubusercontent.com/30337494/111512109-5bc7f600-878a-11eb-81c5-03389656787c.png)
![image](https://user-images.githubusercontent.com/30337494/111512141-65515e00-878a-11eb-8352-4dd6befcf8ca.png)

**Comment by An00nymushun** [comment]
You only need the plugin.js file, just make sure there is a //META... at the top

**Comment by jryn** [comment]
works now, thankies!
