### ISSUE TITLE
Ability to favorite emoji broken

### ISSUE THREAD

**Issue by bill88t** [An00nymushun/DiscordFreeEmojis#20]
After the latest update you can no longer favorite unavailable emojis.
The "You can't use this emoji now" dialog appears.

**Comment by An00nymushun** [comment]
Does this happen on the server where the emoji is too?

**Comment by bill88t** [comment]
No. As long as it's not animated that is. If it's animated the nitro message is shown.
Sorry for responding so late, mail notifs were off for some reason..

**Comment by bill88t** [comment]
Sorry for the stupid title, I don't know what was in my mind at the time.
