### ISSUE TITLE
Feature request: Option to attach emoji as file

### ISSUE THREAD

**Issue by Jake-Moss** [An00nymushun/DiscordFreeEmojis#21]
Would it be possible to attach the emoji as a file when inserted with text as to no have the link show?

Current behavior
![image](https://user-images.githubusercontent.com/49361082/112745086-207ac200-8fe9-11eb-94fe-678509029b00.png)

Desired behavior 
![image](https://user-images.githubusercontent.com/49361082/112745100-3c7e6380-8fe9-11eb-9185-b825b12fd698.png)

Although I can already see sizing problems

**Comment by An00nymushun** [comment]
There is a version of the plugin that has a split feature, in this repo
It will send the emoji in a different message so the link gets hidden properly

**Comment by Jake-Moss** [comment]
I see thank you
