### ISSUE TITLE
Bug: Adding multiple links from emoji picker concatenates them

### ISSUE THREAD

**Issue by Jake-Moss** [An00nymushun/DiscordFreeEmojis#22]
When shift clicking emojis from the emoji menu they are inserted without spacing. Discord concatenates them to only display the first selected. This is not evident when completing from the message box as a space is already there.

Appending a space to the end of the link would remedy this. #21 Would also fix this.

![image](https://user-images.githubusercontent.com/49361082/112745269-6c7a3680-8fea-11eb-8a98-47766d06f3f6.png)

**Comment by An00nymushun** [comment]
I have considered this when making the plugin, and it would really just be used to make spammy messages quickly
