### ISSUE TITLE
Add sticker support

### ISSUE THREAD

**Issue by SwiftWinds** [An00nymushun/DiscordFreeEmojis#30]

**Comment by An00nymushun** [comment]
When I checked, stickers weren't accessible as gif links, so it would need a third-party service to provide the links, which I'm not really comfortable with.

**Comment by FakeMichau** [comment]
They seem to be apng and if sent directly into chat they won't move.

**Comment by AMTitan** [comment]
An0 you are kinda right where you cant the sticker if the sticker is a gif (you can but it will only be the first frame) but looking at it the syntax it `https://media.discordapp.net/stickers/{id}.png?size=256` example `https://media.discordapp.net/stickers/859969090617344010.png?size=256`

**Comment by An00nymushun** [comment]
Yes, you can get the apng but it won't move if it's sent in the chat.
The plugin would either need to include a conversion library to convert from apng to gif
Or use some sort of external service to create gif links.
The easiest would be just to not have animation, but every single sticker is animated.

**Comment by marcussacana** [comment]
you seem pretty discouraged to add features to the plugin, buddy, can you make an example of how I could modify the current code to send the image as an attachment instead of a link? 
I think this should be a sufficient 'example' so I can make my own implementations, while I know how to program I don't know anything about the discord/betterdiscord API nor am I excited to learn, but I really wanted to implement some features in it.

**Comment by An00nymushun** [comment]
> you seem pretty discouraged to add features to the plugin, buddy, can you make an example of how I could modify the current code to send the image as an attachment instead of a link?
> I think this should be a sufficient 'example' so I can make my own implementations, while I know how to programming I don't know anything about the discord/betterdiscord API nor am I excited to learn, but I really wanted to implement some features in it.

Please don't hijack the discussion with a different topic

**Comment by marcussacana** [comment]
wtf

**Comment by An00nymushun** [comment]
You can test this project, it is quite more complex than the free emojis one so it might break more often.
https://github.com/An00nymushun/DiscordFreeStickers

**Comment by SwiftWinds** [comment]
Closing this since https://github.com/An00nymushun/DiscordFreeStickers exists and works well 👍
