### ISSUE TITLE
Fork submission as official BD plugin

### ISSUE THREAD

**Issue by QbDesu** [An00nymushun/DiscordFreeEmojis#31]
Heya, I forked the BD plugin part of this plugin and essentially rewrote it to use ZLibrary and added some config options.
https://github.com/QbDesu/BetterDiscordAddons/tree/potato/Plugins/Freemoji

According to the license which you probably intended to be LGPLv3 judging from the user script, even if it doesn't say so in the plugin I would not need to ask for permission. But still would you be okay with me releasing the fork to https://betterdiscord.app/?

(contacting you via GitHub issue on here because I don't have other means of contacting you)

**Comment by An00nymushun** [comment]
Alright, as long as I'm properly credited it's fine

**Comment by QbDesu** [comment]
Thanks a lot!
