### ISSUE TITLE
Not working anymore.

### ISSUE THREAD

**Issue by CSKnock** [An00nymushun/DiscordFreeEmojis#32]
The plugin does not put links of the emotes anymore. It simply shows the emote, and when hitting enter, it just shows the text
e.g. 🦖 shows up in the typing box, then it actually sends :t-rex: 

Possible helpful information: I am running this plugin via bdCompat on powercord.

**Comment by QbDesu** [comment]
It won't replace the emote with a link if you have the rights to use the emote in question. So it will only replace emotes that are normally grayed out with links.

**Comment by marcussacana** [comment]
I modded my plugin to me know what emoji is retail and what is unlocked by the plugin

![https://i.imgur.com/TVA9k28.png](https://i.imgur.com/TVA9k28.png)

**Comment by CSKnock** [comment]
It doesn't send me the Clyde message, but does everything else.
I would type the emote (or select it)
![image](https://user-images.githubusercontent.com/22779352/125229201-3f554980-e2a4-11eb-98b5-13e2259882f1.png)
It would show that, and when I go to send it
![image](https://user-images.githubusercontent.com/22779352/125229257-6ca1f780-e2a4-11eb-8dd9-9af3b45835df.png)
It turns into this.

**Comment by An00nymushun** [comment]
That's likely because some other plugin that spoofs your nitro status

**Comment by CSKnock** [comment]
Update, I moved back to BetterDiscord, and it's all resolved, Sorry!
