### ISSUE TITLE
Emoji that exceed the limit of server slots that have lost the boost level are not sent

### ISSUE THREAD

**Issue by l-Nuril-l** [An00nymushun/DiscordFreeEmojis#34]
When my server was level 3, I loaded 250 emojis, when the level went down, there were only 50 unlocked slots left, but there are 250 more in the list of emojis.
The plugin does not parse blocked emojis(locked emoji are gray in server settings). Although nothing has changed in the code of the smiley element, I can also get the link manually.
[Google Translate]
```
//sends
<li role="gridcell" aria-rowindex="6" aria-colindex="1" id="emoji-picker-grid-0-5" tabindex="-1" class="emojiItem-14v6tW emojiItemMedium-_WAwGB emojiItemDisabled-1FvFuF"><img class="image-1CmAz0" alt=":1e2747c8b64efb44c6b0925be121ca96:" src="https://cdn.discordapp.com/emojis/853115310949007390.png?size=32" aria-label=":1e2747c8b64efb44c6b0925be121ca96:" style="background-size: 32px; height: 32px; width: 32px;"></li>
```
```
//not sends
<li role="gridcell" aria-rowindex="6" aria-colindex="2" id="emoji-picker-grid-1-5" tabindex="-1" class="emojiItem-14v6tW emojiItemMedium-_WAwGB emojiItemDisabled-1FvFuF"><img class="image-1CmAz0" alt=":1e3288e50613013b9cc1ffbe9c39a1e9:" src="https://cdn.discordapp.com/emojis/853130708372553738.png?size=32" aria-label=":1e3288e50613013b9cc1ffbe9c39a1e9:" style="background-size: 32px; height: 32px; width: 32px;"></li>
```
PS. Your new plugin for sending stickers works with blocked stickers on my 0 level server. Thanks for him.
Invite code to my server if needed -> dQJNqcY

**Comment by l-Nuril-l** [comment]
> You will have to invite me to a server that has this kind of emojis

> Invite code to my server if needed -> dQJNqcY

https://discord.gg/dQJNqcY
P.S. I can give you access to the emoji if you need it.

**Comment by An00nymushun** [comment]
Okay, try
https://raw.githubusercontent.com/An00nymushun/DiscordFreeEmojis/master/DiscordFreeEmojisSplit48px.plugin.js

**Comment by l-Nuril-l** [comment]
It works, thanks.
