### ISSUE TITLE
`emojisModule not found`

### ISSUE THREAD

**Issue by smowtenshi** [An00nymushun/DiscordFreeEmojis#39]
```js
[FreeEmojis] emojisModule not found.
(anonymous) @ 443da8b182aaf308ce76.js:130
```

with environment:

Stable 104276 (4adab42)
BetterDiscord 1.2.4
Host 0.0.16 Linux 64-Bit (5.14.10-1-MANJARO)

Current plugin version: 1.5

**Comment by Nitaray** [comment]
Same problem, just happened today. It was still working this morning

**Comment by An00nymushun** [comment]
It should be fixed now, they changed the name of a method randomly

**Comment by smowtenshi** [comment]
It seems to work fine now, thanks.
