### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by rxpsam420** [An00nymushun/DiscordFreeEmojis#41]
The plugins hasnt been working for the past 2 days, every time I select an emoji its telling me to buy nitro

**Comment by Luysita** [comment]
Same problem here

**Comment by An00nymushun** [comment]
Which version are you using?

**Comment by Luysita** [comment]
DiscordFreeEmojisv1.4

**Comment by An00nymushun** [comment]
Make sure you are using the latest version

**Comment by Luysita** [comment]
I tried to install the newest version and now I can't load emojis at all it's crashing my Discord now.
What files am I suppose to install?

**Comment by An00nymushun** [comment]
Ah so you have been using the installer, I wondered if anyone used that, alright I will update those too when I get the chance

**Comment by Luysita** [comment]
I uninstalled all plugins, disabled the ones I have and I'm still having issues with Discord crashing when clicking the emoji icon
https://i.imgur.com/lJwtkyx.png

How do I fix this now?

**Comment by An00nymushun** [comment]
Do you have BD or have you always been using the installer?

**Comment by Luysita** [comment]
I got BD, I downloaded them and placed on the plugin folder

**Comment by An00nymushun** [comment]
Show the Ctrl-Shift-I console errors and tell me exactly which file you are using

**Comment by Luysita** [comment]
Using these plugins
https://i.imgur.com/lInZCO6.png

Console error when trying to use emojis
`4DevTools failed to load source map: Could not load content for https://discord.com/assets/1355d3d03c7068e2af61.worker.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error
cce880051e247eefbd29.js:130 [BDFDB] (v1.9.8) Loading Library
cce880051e247eefbd29.js:130 [XenoLib] Failed to create special parser TypeError: Cannot read property 'voiceChannels' of undefined
    at t.default (31e141f27aafd6634fd3.js:1482)
    at 1XenoLib.plugin.js:1057
    at buildPlugin (1XenoLib.plugin.js:1071)
    at 1XenoLib.plugin.js:2269
    at 1XenoLib.plugin.js:2270
    at 1XenoLib.plugin.js:2276
    at Object.getFileModification (<anonymous>:4:308691)
    at Object..js (<anonymous>:4:269335)
    at Function.t._load (<anonymous>:4:371583)
    at Object.loadAddon (<anonymous>:4:269492)
    at Object.loadAddon (<anonymous>:4:307016)
    at Object.loadAllAddons (<anonymous>:4:272132)
    at Object.initialize (<anonymous>:4:266622)
    at Object.initialize (<anonymous>:4:306226)
    at Object.startup (<anonymous>:4:368212)
(anonymous) @ cce880051e247eefbd29.js:130
stacktrace @ 0PluginLibrary.plugin.js:1697
stacktrace @ 0PluginLibrary.plugin.js:4084
(anonymous) @ 1XenoLib.plugin.js:1063
buildPlugin @ 1XenoLib.plugin.js:1071
(anonymous) @ 1XenoLib.plugin.js:2269
(anonymous) @ 1XenoLib.plugin.js:2270
(anonymous) @ 1XenoLib.plugin.js:2276
getFileModification @ VM400:4
(anonymous) @ VM400:4
Module.load @ VM43 loader.js:935
Module._load @ VM43 loader.js:776
f._load @ VM70 asar_bundle.js:5
o._load @ VM75 renderer_init.js:33
t._load @ VM400:4
Module.require @ VM43 loader.js:959
require @ VM50 helpers.js:88
loadAddon @ VM400:4
loadAddon @ VM400:4
loadAllAddons @ VM400:4
initialize @ VM400:4
initialize @ VM400:4
startup @ VM400:4
async function (async)
startup @ VM400:4
(anonymous) @ VM400:4
n @ VM400:4
(anonymous) @ VM400:4
(anonymous) @ VM400:4
(anonymous) @ VM400:9
e.startsWith.e.startsWith.WebFrame.<computed> @ VM75 renderer_init.js:89
(anonymous) @ VM75 renderer_init.js:117
(anonymous) @ VM75 renderer_init.js:101
emit @ VM14 events.js:315
onMessage @ VM75 renderer_init.js:93
DevTools failed to load source map: Could not load content for https://discord.com/assets/b244897e78d949d00f7d.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
cce880051e247eefbd29.js:130 [XenoLib] version 1.3.43 has started.
cce880051e247eefbd29.js:130 [AutoPlayGifs] version 0.1.4 has started.
cce880051e247eefbd29.js:130 [CallTimeCounter] version 0.0.3 has started.
cce880051e247eefbd29.js:130 [EmojiUtilities] version 0.0.9 has started.
cce880051e247eefbd29.js:130 [FreeStickers] Started!
cce880051e247eefbd29.js:130 [BetterDiscord] [PluginManager] Starting to watch plugin addons.
cce880051e247eefbd29.js:130 [BetterDiscord] [Startup] Loading Themes
cce880051e247eefbd29.js:130 [BetterDiscord] [ThemeManager] Starting to watch theme addons.
cce880051e247eefbd29.js:130 [BetterDiscord] [Startup] Removing Loading Icon
cce880051e247eefbd29.js:130 [BetterDiscord] [Startup] Collecting Startup Errors
cce880051e247eefbd29.js:130 [GatewaySocket] [READY] took 2930ms, via ["gateway-prd-main-2g1w",{"micros":969942,"calls":["discord-sessions-blue-prd-2-18",{"micros":907761,"calls":["start_session",{"micros":255664,"calls":["api-prd-main-lvd8",{"micros":215997,"calls":["get_user",{"micros":6673},"add_authorized_ip",{"micros":9309},"get_guilds",{"micros":8080},"private_channels",{"micros":55475},"read_states",{"micros":42961},"coros_wait",{"micros":47560},"aliases",{"micros":8269},"experiments",{"micros":4902}]}]},"guilds_connect",{"micros":12651,"calls":[]},"presence_connect",{"micros":2,"calls":[]}]}]}] as 99e46d6514a73ab05e1a39bbe9780af1
cce880051e247eefbd29.js:130 [AuthenticationStore] handleConnectionOpen called {tokenManagerHasToken: true, storageHasToken: true}
cce880051e247eefbd29.js:130 [NativeDispatchUtils] Tried getting Dispatch instance before instantiated
(anonymous) @ cce880051e247eefbd29.js:130
(anonymous) @ 29b0241324f43bcdb80c.js:2068
warn @ 29b0241324f43bcdb80c.js:3906
m @ 29b0241324f43bcdb80c.js:3721
setCredentials @ 29b0241324f43bcdb80c.js:3724
H @ 29b0241324f43bcdb80c.js:2766
CONNECTION_OPEN @ 29b0241324f43bcdb80c.js:2769
t._dispatch @ 29b0241324f43bcdb80c.js:3987
t.dispatch @ 29b0241324f43bcdb80c.js:3986
(anonymous) @ 29b0241324f43bcdb80c.js:2813
Ee @ 29b0241324f43bcdb80c.js:2810
(anonymous) @ 29b0241324f43bcdb80c.js:2813
a.emit @ 29b0241324f43bcdb80c.js:4916
n._handleDispatch @ 29b0241324f43bcdb80c.js:1735
(anonymous) @ 29b0241324f43bcdb80c.js:1733
(anonymous) @ 29b0241324f43bcdb80c.js:1733
l.push.t.handleFlushEnd @ 29b0241324f43bcdb80c.js:1723
d.push @ 29b0241324f43bcdb80c.js:5716
l.push.t.feed @ 29b0241324f43bcdb80c.js:1723
(anonymous) @ 29b0241324f43bcdb80c.js:1733
cce880051e247eefbd29.js:130 [MessageActionCreators] Fetching messages for 412564246921084929 between undefined and undefined. jump=undefined
cce880051e247eefbd29.js:130 [Flux] Slow dispatch on CONNECTION_OPEN: 165ms
cce880051e247eefbd29.js:130 [Flux] Slow batch emitChanges took 455ms recentActions: GAMES_DATABASE_FETCH -> CALL_CONNECT -> ACTIVITY_UPDATE_START -> LOAD_MESSAGES -> BILLING_MOST_RECENT_SUBSCRIPTION_FETCH_START -> USER_SETTINGS_UPDATE -> EXPERIMENT_TRIGGER -> TUTORIAL_INDICATOR_HIDE -> TRACK -> TRACK
cce880051e247eefbd29.js:130 [GatewaySocket] [READY_SUPPLEMENTAL] took 3727ms
cce880051e247eefbd29.js:130 [Flux] Slow batch emitChanges took 297ms recentActions: USER_SETTINGS_UPDATE -> EXPERIMENT_TRIGGER -> TUTORIAL_INDICATOR_HIDE -> TRACK -> TRACK -> TRACK -> DRAFT_CHANGE -> TYPING_STOP_LOCAL -> CONNECTION_OPEN_SUPPLEMENTAL -> VOICE_STATE_UPDATES
cce880051e247eefbd29.js:130 [MessageActionCreators] Fetched 50 messages for 412564246921084929 isBefore:false isAfter:false
cce880051e247eefbd29.js:130 [Flux] Slow batch emitChanges took 210ms recentActions: PRESENCE_UPDATE -> PRESENCE_UPDATE -> GUILD_MEMBER_ADD -> MESSAGE_UPDATE -> STATUS_PAGE_SCHEDULED_MAINTENANCE -> CHECKING_FOR_UPDATES -> ACTIVITY_UPDATE_SUCCESS -> BILLING_MOST_RECENT_SUBSCRIPTION_FETCH_SUCCESS -> LIBRARY_FETCH_SUCCESS -> LOAD_MESSAGES_SUCCESS
cce880051e247eefbd29.js:130 [Flux] Slow dispatch on LOAD_MESSAGES_SUCCESS: 218ms
cce880051e247eefbd29.js:130 [BetterDiscord] [Emotes] BTTV
cce880051e247eefbd29.js:130 [MessageActionCreators] Fetching messages for 412564246921084929 between undefined and undefined. jump=undefined
cce880051e247eefbd29.js:130 [MessageActionCreators] Fetched 50 messages for 412564246921084929 isBefore:false isAfter:false
cce880051e247eefbd29.js:130 [BetterDiscord] [Emotes] FrankerFaceZ
cce880051e247eefbd29.js:130 [MessageLoggerV2] ImageCacheServer: OK
cce880051e247eefbd29.js:130 [Flux] Slow dispatch on GAMES_DATABASE_UPDATE: 122ms
cce880051e247eefbd29.js:130 [BDFDB] (v1.9.8) Finished loading Library
cce880051e247eefbd29.js:130 [CompleteTimestamps] (v1.6.0) has been started
cce880051e247eefbd29.js:130 [PinDMs] (v1.8.5) has been started
cce880051e247eefbd29.js:130 [RunningGameStore] games [{…}]
cce880051e247eefbd29.js:130 [RTCLatencyTestManager] RTC cached preferred region is europe
cce880051e247eefbd29.js:130 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at nl (29b0241324f43bcdb80c.js:6045)
    at e (29b0241324f43bcdb80c.js:5984)
    at Bo (29b0241324f43bcdb80c.js:5996)
    at $s (29b0241324f43bcdb80c.js:6041)
    at Gu (29b0241324f43bcdb80c.js:6031)
    at Uu (29b0241324f43bcdb80c.js:6031)
    at wu (29b0241324f43bcdb80c.js:6031)
    at Au (29b0241324f43bcdb80c.js:6028)
    at 29b0241324f43bcdb80c.js:5973
    at t.unstable_runWithPriority (29b0241324f43bcdb80c.js:6272)
    at Ki (29b0241324f43bcdb80c.js:5973)
    at Xi (29b0241324f43bcdb80c.js:5973)
    at qi (29b0241324f43bcdb80c.js:5973)
    at we (29b0241324f43bcdb80c.js:6050)
    at en (29b0241324f43bcdb80c.js:5950)
    at HTMLDivElement.r (cce880051e247eefbd29.js:126)
(anonymous) @ cce880051e247eefbd29.js:130
Es @ 29b0241324f43bcdb80c.js:6016
a.componentDidCatch.n.callback @ 29b0241324f43bcdb80c.js:6016
pa @ 29b0241324f43bcdb80c.js:5976
Ss @ 29b0241324f43bcdb80c.js:6018
Bu @ 29b0241324f43bcdb80c.js:6036
t.unstable_runWithPriority @ 29b0241324f43bcdb80c.js:6272
Ki @ 29b0241324f43bcdb80c.js:5973
Vu @ 29b0241324f43bcdb80c.js:6032
Au @ 29b0241324f43bcdb80c.js:6028
(anonymous) @ 29b0241324f43bcdb80c.js:5973
t.unstable_runWithPriority @ 29b0241324f43bcdb80c.js:6272
Ki @ 29b0241324f43bcdb80c.js:5973
Xi @ 29b0241324f43bcdb80c.js:5973
qi @ 29b0241324f43bcdb80c.js:5973
we @ 29b0241324f43bcdb80c.js:6050
en @ 29b0241324f43bcdb80c.js:5950
r @ cce880051e247eefbd29.js:126
cce880051e247eefbd29.js:132 POST https://sentry.io/api/140984/store/?sentry_key=fa97a90475514c03a42f80cd36d147c4&sentry_version=7 429 (Too Many Requests)`

**Comment by An00nymushun** [comment]
Please only use one of the plugin files, no need for the meta file or anything else from this repo
Looking at the logs, it doesn't seem like the plugin is even enabled

**Comment by Luysita** [comment]
Yea but even with the plugins disabled Discord is completely broken now...

**Comment by An00nymushun** [comment]
Disable all plugins

**Comment by Luysita** [comment]
I literally deleted all the plugins and still have the same issue :/

**Comment by Luysita** [comment]
The installer doesn't work for me

**Comment by Luysita** [comment]
https://i.imgur.com/AmRfE7G.png

Having this issue when placing the file in plugins folder on BD

**Comment by An00nymushun** [comment]
Please make sure you downloaded it properly

**Comment by Luysita** [comment]
How do I download it properly? I've been right/alt clicking it like you said

**Comment by sapphic-wallflower** [comment]
Open Terminal, change the directory to where you want to download the items and type: 
* `git clone https://github.com/An00nymushun/DiscordFreeEmojis.git`

If you're on Windows, 
* Go here [here](https://github.com/An00nymushun/DiscordFreeEmojis)
* Click `Code`
* Click `Download as ZIP`
* Extract the archive and move `DiscordFreeEmojis.plugin.js` or `DiscordFreeEmojis64px.plugin` to your BD plugins folder.

**Comment by rxpsam420** [comment]
I installed the lasted version from here and this happens whenever I click on emojis, I can still use the emojis only from keyboard using ':'

![image](https://user-images.githubusercontent.com/93736794/141539765-f86b4fa5-55cd-43aa-b150-017b75da635a.png)

**Comment by An00nymushun** [comment]
Which file are you using exactly?

**Comment by rxpsam420** [comment]
> Which file are you using exactly?

I tried both DiscordFreeEmojis.plugin.js and DiscordFreeEmojis64px.plugin.js, and both had the same problem

**Comment by An00nymushun** [comment]
Turn off all your other plugins and restart Discord

**Comment by rxpsam420** [comment]
Disabled all plugin and also removed them, restarted discord and still facing the same issue

**Comment by Luysita** [comment]
> 
> 
> Disabled all plugin and also removed them, restarted discord and still facing the same issue
> 
> Edit: And I got this error when I clicked on emojis ![image](https://user-images.githubusercontent.com/93736794/141688009-9c235679-fe09-4a16-af47-3edfbd2b985a.png)

Go to BD settings and disable "Emote System"

**Comment by rxpsam420** [comment]
> > Disabled all plugin and also removed them, restarted discord and still facing the same issue
> > Edit: And I got this error when I clicked on emojis ![image](https://user-images.githubusercontent.com/93736794/141688009-9c235679-fe09-4a16-af47-3edfbd2b985a.png)
> 
> Go to BD settings and disable "Emote System"

It worked! Thank you so much <333

**Comment by EvilFlame112** [comment]
This problem still persists... tried downloading from the repository, used 64px version and the normal one, got the one from BD's official site and nothing seems to work. My BD emote system is disabled and i have no other plugins.

**Comment by An00nymushun** [comment]
Which BD version do you have, which discord (ptb, normal, canary)? Send a pic of your plugins folder. Also, does it happen when you click on available emotes or only with gray ones?

**Comment by Russian-kun** [comment]
The problem was with the BD update. The latest one fixes this bug (at least for me).

**Comment by SwiftWinds** [comment]
Had the same problem with the crashes and such and what fixed it was updating BD to the latest and DiscordFreeEmojis to v1.6. 👍
