### ISSUE TITLE
Please add feature to copy link from emoji bar

### ISSUE THREAD

**Issue by Koten-Kostiantyn** [An00nymushun/DiscordFreeEmojis#44]
Please add a button to copy link from here 

![image](https://user-images.githubusercontent.com/15310858/146581941-7b6adbcd-1e80-4b17-8b52-d8ff43198643.png)

You can actually drag an image from discord application to your browser and it will convert it to a link
So in theory this should work =D

![image](https://user-images.githubusercontent.com/15310858/146582077-d5c4e8a5-e11b-4227-bfff-c0f5fa91a7b9.png)
![image](https://user-images.githubusercontent.com/15310858/146582383-9198bbee-dfb1-4ff2-a292-8096f374d5d1.png)

![image](https://user-images.githubusercontent.com/15310858/146582312-cee9fff5-3b35-4e8f-ae94-066f07ddf4f0.png)

**Comment by An00nymushun** [comment]
I don't really understand why.
You can just click on it to get the link and it's hard to move your cursor there without the selected emoji changing.
Just make yourself a private server and use the plugin in the chat there.

**Comment by Koten-Kostiantyn** [comment]
With this plugin I can re-use only already posted emoji in channel. But if there were button, I can choose from millions emoji. If you don't have nitro, it's easy, just click it, click "X" to close nitro pop-up, and it will stay there. Now you can copy it easy
I mean, if there were a button there wouldn't be a need to drag it to browser to get a link, wich is bit uncomfortable

**Comment by An00nymushun** [comment]
I don't think you understand how to use the plugin, or maybe some other plugin is interfering with it?
If you have external emojis permissions, you can just click on any of the greyed-out emojis to get the link put in the message input.

**Comment by Koten-Kostiantyn** [comment]
How do you do it? I have installed it properly, but there is no way to copy link from gray emoji in emoji bar

**Comment by Koten-Kostiantyn** [comment]
Yeah, seems like It did not installed smh. I installed BetterDiscord and it has added copy link button but not this plugin. I did put it in plugins but still doesn't work. Tried installing with PowerShell but still. idk what's wrong

**Comment by Koten-Kostiantyn** [comment]
I see, I have copied the most recent version of plugin for BetterDiscord and now it's working Yay

Just somewhere is outdated plugin I have found

**Comment by An00nymushun** [comment]
Alright
