### ISSUE TITLE
It ain't working, chief

### ISSUE THREAD

**Issue by TheK0tYaRa** [An00nymushun/DiscordFreeEmojis#46]
***In case you don't know where the bug is in the code or what exactly causes it.***

**Describe the bug**
The plugin for BBD is currently not working on Linux.

**To Reproduce**
I have disabled every plugin except this one by moving them to a different dir. It's still not working. It may be lacking some dependency check.

1. Install it
2. Try to send a nitro emoji
3. Fail

**Expected behavior**
An emoji is sent on step 3

**Screenshots**
![image](https://user-images.githubusercontent.com/27967034/153773472-179ab563-a359-47c9-adb8-44591cb558a7.png)
![image](https://user-images.githubusercontent.com/27967034/153773478-28de7075-3573-4af7-ad21-6c494ce3b09d.png)
console when switching to DM
![image](https://user-images.githubusercontent.com/27967034/153773507-96992cb4-eee8-4093-909f-c8424dafe2c0.png)

**Client:**
 - Desktop [Linux, Arch-like]
 - Discord Build Channel [Release]
 - Plugin Version [1.1 in code, 1.4 in BD, i didn't change that]
 - BD Version [1.5.1]

**Additional context**
None.

**Comment by An00nymushun** [comment]
You aren't using the newest version

**Comment by LoSunny** [comment]
People seems to be downloading from https://betterdiscord.app/plugin/FreeEmojis which has an old version, maybe someone can update it?

**Comment by An00nymushun** [comment]
It's because it was a fork that was linked to the site https://github.com/BetterDiscordPlugins/DiscordFreeEmojis
I can't update that
