### ISSUE TITLE
Not working - "META was not found."

### ISSUE THREAD

**Issue by GloppyBoopin** [An00nymushun/DiscordFreeEmojis#55]
The README is awful. It doesn't explain what all the files are and what needs to be installed for it to work.

I've ran the powershell script, I downloaded all the files that seemed necessary (`meta`, `plugin`, `user`) 

![image](https://user-images.githubusercontent.com/64323692/192771944-17cb098f-9160-4bb5-8967-b2871ca2a8f1.png)

Deleted these files 1 by 1 and re-added them to plugins folder, nothing changes - it always shows this "META was not found." message. The plugin doesn't show up in the plugins list inside Discord itself.

* Stable 149549 (1e1ae6d)
* Host 1.0.9006
* Windows 10 64-Bit (10.0.19044)
* BD 1.7.0
* Plugin 1.7

**Comment by GloppyBoopin** [comment]
And yes, FreeStickers doesn't work too

**Comment by An00nymushun** [comment]
Make sure you are using the newest version. Also, you likely downloaded some HTML instead of the source code.
It's only the plugin file that's needed for BD.

**Comment by GloppyBoopin** [comment]
Works, my bad
