### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by wu9411194** [An00nymushun/DiscordFreeEmojis#58]
I tried for a long time, but it still doesn't work.
Nothing happens after clicking.
![image](https://user-images.githubusercontent.com/115206931/194472266-5900ff1e-e146-45d0-aef6-b4790863a010.png)
![image](https://user-images.githubusercontent.com/115206931/194472341-ffce4d11-6d56-4547-a159-d03b631c358f.png)

**Comment by wu9411194** [comment]
Plugin Version [1.6]
BD Version (1.7.0)

**Comment by An00nymushun** [comment]
Current plugin version is 1.7
