### ISSUE TITLE
Broken by latest update

### ISSUE THREAD

**Issue by Evan109** [An00nymushun/DiscordFreeEmojis#61]
**Describe the bug**
The plugin seems to be broken by the latest discord update.

**To Reproduce**
Using v1.8.0 BetterDiscord, V1.6 of DiscordFreeEmojis and disable all other plugins

1. Go to Emoji Menu
2. Click on an animated emoji
3. Observe Discord Nitro requirement rather than successful link generation
4. See error "You can't use this emoji right now"

Tried restarting discord quite a few times with various states.

**Expected behavior**
Adding the link to the emoji properly

**Screenshots**
Check Ctrl-Shift-I console for red error logs!

**Client:**
 - Browser Opera GX / Desktop Windows 10.0.19043
 - Discord Release Build - Stable 151857 (383a8ed)
 - Plugin Version 1.7
 - BD Version 1.8.0

**Additional context**
Been broken for like 2 weeks, tried a few things without success over that time

**Comment by Evan109** [comment]
Tried reinstalling betterdiscord and the plugin, no dice.

**Comment by Evan109** [comment]
AHA something useful. I got console to work and it seems like you're using a depricated function
![image](https://user-images.githubusercontent.com/35783870/195214279-27183fe0-986c-4967-9414-63a91c9802f7.png)

the full link address to the files:
https://discord.com/assets/1e87e1668b62877ceab6.js
https://discord.com/assets/1e87e1668b62877ceab6.js

**Comment by Acfkun** [comment]
The problem is already solved in version 1.7 that is here on github, apparently the BetterDiscord page has not updated it yet

**Comment by Evan109** [comment]
When I replace DiscordFreeEmojis64px.plugin.js with the new version, it errors out on launch with "META not found."
when I add DiscordFreeEmojis.meta.js there is no change.
I also tried adding …user.js, and ...64px.user.js with no success.

**Comment by Acfkun** [comment]
I don't know why this happens to you, I practically have no idea of code or programming so I can't help you, if you want you can try to reinstall Better discord,because all I did was download the .zip with all the code and replace the old "DiscordFreeEmojis64px. plugin.js" I had with the new plugin from the .zip, I didn't have any errors and the plugin works perfectly for me.
I hope you can fix it.

**Comment by Evan109** [comment]
I downloaded the file directly and it didn't work, I downloaded the zip with the file in it, cherrypicked the file, and it worked.
?
at least it's fixed for me.
closing this issue, the root cause is that betterdiscord's website is still distributing v1.6, which is broken.
