### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by luftwafflezz** [An00nymushun/DiscordFreeEmojis#62]
**Describe the bug**
Whenever I run the userscript, it brings up this error: 
![image](https://user-images.githubusercontent.com/72886318/196699333-6d070c91-4f1d-479d-8a52-317549ab9ab8.png)

**To Reproduce**
Just run the userscript.

**Client:**
 - Browser: Firefox / OS: Windows 11
 - Discord Build Channel: Release
 - Plugin Version: Latest
 - BD Version: 1.8.2

**Comment by PixelGuy123** [comment]
Just to make this clear, when you install the user script, you DON'T run it, instead, use an extension like tampermonkey to run it
You may download the file with tampermonkey, so it asks if you want to install IN it

**Comment by luftwafflezz** [comment]
Okay, it would be useful if that were noted in readme.md.
