### ISSUE TITLE
not working???

### ISSUE THREAD

**Issue by Wasimsha45435** [An00nymushun/DiscordFreeEmojis#69]
***In case you don't know where the bug is in the code or what exactly causes it.***

**Describe the bug**

**To Reproduce**
`If you use other plugins, disable all of them to figure out which ones are necessary to reproduce your issue, if any.`

`Make sure you can reproduce this problem yourself with your steps after restarting Discord!`

**Expected behavior**

**Screenshots**
Check Ctrl-Shift-I console for red error logs!

**Client:**
 - Browser [which browser] / Desktop [OS]
 - Discord Build Channel [Release / PTB / Canary]
 - Plugin Version [e.g. 1.2]
 - BD Version (if applicable)

**Additional context**

**Comment by unholypersona** [comment]
if you don't know by now a discord update broke tons of the plugins including this one

**Comment by killshotroxs** [comment]
so is there a alternative to this??

**Comment by killshotroxs** [comment]
> if you don't know by now a discord update broke tons of the plugins including this one

Help with another alternative.... i need freeEmojis Lol

**Comment by unholypersona** [comment]
so I just found out that the patch has been already released just copy the code
![image](https://user-images.githubusercontent.com/113929815/203134656-f67168f9-4845-48fe-8d31-a19e6024f53c.png)
navigate to plugins and then press this
![image](https://user-images.githubusercontent.com/113929815/203135019-30515399-42d3-4b50-8892-e65664e5784e.png)
and replace the old code with the new one

**Comment by unholypersona** [comment]
@Wasimsha45435 you may close this issue now since it's been most likely solved

**Comment by Wasimsha45435** [comment]
yeah thanks just saw it, it worked
