### ISSUE TITLE
are there gonna be color previews?

### ISSUE THREAD

**Issue by mutschistink** [An00nymushun/DiscordFreeEmojis#70]

**Comment by ReedGraf** [comment]
Did you just put the unmodified template as your issue? Bruh

**Comment by moosje2003** [comment]
just use the EmoteReplacer plugin

**Comment by mutschistink** [comment]
> Did you just put the unmodified template as your issue? Bruh

bruh i just want to know how to get color previews

**Comment by mutschistink** [comment]
> .emojiItemDisabled-3VVnwp {
>    filter: grayscale(0%);
> }

bro i luv you thx <3
