### ISSUE TITLE
Nothing is working

### ISSUE THREAD

**Issue by SkyKingPX** [An00nymushun/DiscordFreeEmojis#76]
***In case you don't know where the bug is in the code or what exactly causes it.***

**Describe the bug**
I can´t use the Emojis from other servers

1. Go to a Server
2. Click on Emoji menu
3. Scroll down to any server emoji
4. See error - its grey

**Screenshots**
![image](https://user-images.githubusercontent.com/95442431/210132085-e03c0655-6079-48c2-83c5-9928e63ea8c8.png)

**Client:**
 - Plugin Version: 1.6
 - BD Version: 1.8.4

**Comment by d-Dice** [comment]
Same problem

**Comment by Zigatronz** [comment]
Same

**Comment by MeanXBeam** [comment]
i think its broken

**Comment by Boda69** [comment]
same

**Comment by gcordeiroc** [comment]
same

**Comment by SkyKingPX** [comment]
**WHY NO ONE ANWERS!**

**Comment by longnp1610** [comment]
> **WHY NO ONE ANWERS!**

Plugin works well, the emoji is gray but you can still use it. Just click on emojis you want and send.

**Comment by SkyKingPX** [comment]
@longnp1610 No. I can't. If I press it then I only see "by Nitro to use all Emojis"

**Comment by longnp1610** [comment]
Hmm, weird. My BD core v1.8.4 and Plugin is v1.7

**Comment by DivinePradhan** [comment]
> Hmm, weird. My BD core v1.8.4 and Plugin is v1.7

Bro i know it most of the people's plugin version is 1.6 and my plugin version is also 1.6 can you send me the new plugin via discord? my discord id is: DivinePradhan#5185
![image](https://user-images.githubusercontent.com/122522718/212025984-556ee738-270a-4228-b336-ed64072ee6f0.png)

**Comment by longnp1610** [comment]
> > Hmm, weird. My BD core v1.8.4 and Plugin is v1.7
> 
> Bro i know it most of the people's plugin version is 1.6 and my plugin version is also 1.6 can you send me the new plugin via discord? my discord id is: DivinePradhan#5185 ![image](https://user-images.githubusercontent.com/122522718/212025984-556ee738-270a-4228-b336-ed64072ee6f0.png)

Hey bro, the latest version is also on this git repo, you can download the script file or copy-paste the new code into your plugin (by clicking on the Edit button and pasting the code in it). If you still need help, find me on Discord (EL#4090)
Check the repo [here](https://github.com/An00nymushun/DiscordFreeEmojis/blob/master/DiscordFreeEmojis64px.plugin.js).

**Comment by SkyKingPX** [comment]
@longnp1610 I will also test it 😅

**Comment by SkyKingPX** [comment]
@longnp1610 This version is working, but it´s not really an Emoji
