### ISSUE TITLE
[Discord Breaking Change] Can't send emojis

### ISSUE THREAD

**Issue by EpicGazel** [An00nymushun/DiscordFreeEmojis#86]
## Edit: Check out my fork I plan to maintain https://github.com/EpicGazel/DiscordFreeEmojis. Just download it from there.

Discord seems to no longer offer emoji.url in the emoji object, so we have to make the link ourselves now.

- ctrl + f/find  "function replaceEmoji"
- ``const emojiUrl = `https://cdn.discordapp.com/emojis/${emoji.id}.${emoji.animated ? "gif" : "webp"}`;``
- ``parseResult.content = parseResult.content.replace(`<${emoji.animated ? "a" : ""}:${emoji.originalName || emoji.name}:${emoji.id}>`,emojiUrl);``
- Delete the original `parseResult.content = ...`

If you want to hide the character when embedding by using a hyperlink use the following instead:
``parseResult.content = parseResult.content.replace(`<${emoji.animated ? "a" : ""}:${emoji.originalName || emoji.name}:${emoji.id}>`,`[᲼](${emojiUrl})`);``

**Comment by EpicGazel** [comment]
You can also add back the "?size=64" to the end of the emojiUrl to lock its size as it is by default.

**Comment by Oqarshi** [comment]
> Discord seems to no longer offer emoji.url in the emoji object, so we have to make the link ourselves now.
> 
> * ctrl + f/find  "function replaceEmoji"
> * `` const emojiUrl = `https://cdn.discordapp.com/emojis/${emoji.id}.${emoji.animated ? "gif" : "webp"}`; ``
> * `` parseResult.content = parseResult.content.replace(`<${emoji.animated ? "a" : ""}:${emoji.originalName || emoji.name}:${emoji.id}>`,emojiUrl); ``
> * Delete the original `parseResult.content = ...`
> 
> If you want to hide the character when embedding by using a hyperlink use the following instead: `` parseResult.content = parseResult.content.replace(`<${emoji.animated ? "a" : ""}:${emoji.originalName || emoji.name}:${emoji.id}>`,`[᲼](${emojiUrl})`); ``

This worked than you! But im not sure this plugin is maintained anymore 😞

**Comment by swaggyP36000** [comment]
> > Discord seems to no longer offer emoji.url in the emoji object, so we have to make the link ourselves now.
> > 
> > * ctrl + f/find  "function replaceEmoji"
> > * `` const emojiUrl = `https://cdn.discordapp.com/emojis/${emoji.id}.${emoji.animated ? "gif" : "webp"}`; ``
> > * `` parseResult.content = parseResult.content.replace(`<${emoji.animated ? "a" : ""}:${emoji.originalName || emoji.name}:${emoji.id}>`,emojiUrl); ``
> > * Delete the original `parseResult.content = ...`
> > 
> > If you want to hide the character when embedding by using a hyperlink use the following instead: `` parseResult.content = parseResult.content.replace(`<${emoji.animated ? "a" : ""}:${emoji.originalName || emoji.name}:${emoji.id}>`,`[᲼](${emojiUrl})`); ``
> 
> This worked than you! But im not sure this plugin is maintained anymore 😞

is there any similar that is maintained for bd?

**Comment by Haidex** [comment]
> Discord seems to no longer offer emoji.url in the emoji object, so we have to make the link ourselves now.
> 
> * ctrl + f/find  "function replaceEmoji"
> * `` const emojiUrl = `https://cdn.discordapp.com/emojis/${emoji.id}.${emoji.animated ? "gif" : "webp"}`; ``
> * `` parseResult.content = parseResult.content.replace(`<${emoji.animated ? "a" : ""}:${emoji.originalName || emoji.name}:${emoji.id}>`,emojiUrl); ``
> * Delete the original `parseResult.content = ...`
> 
> If you want to hide the character when embedding by using a hyperlink use the following instead: `` parseResult.content = parseResult.content.replace(`<${emoji.animated ? "a" : ""}:${emoji.originalName || emoji.name}:${emoji.id}>`,`[᲼](${emojiUrl})`); ``

where am i supposed to input those? any screen on discord?

**Comment by fuwa120** [comment]
> > Discord seems to no longer offer emoji.url in the emoji object, so we have to make the link ourselves now.
> > 
> > * ctrl + f/find  "function replaceEmoji"
> > * `` const emojiUrl = `https://cdn.discordapp.com/emojis/${emoji.id}.${emoji.animated ? "gif" : "webp"}`; ``
> > * `` parseResult.content = parseResult.content.replace(`<${emoji.animated ? "a" : ""}:${emoji.originalName || emoji.name}:${emoji.id}>`,emojiUrl); ``
> > * Delete the original `parseResult.content = ...`
> > 
> > If you want to hide the character when embedding by using a hyperlink use the following instead: `` parseResult.content = parseResult.content.replace(`<${emoji.animated ? "a" : ""}:${emoji.originalName || emoji.name}:${emoji.id}>`,`[᲼](${emojiUrl})`); ``
> 
> where am i supposed to input those? any screen on discord?

Go into your BetterDiscord plugins menu and click the Edit button for DiscordFreeEmojis and then input it there, at line 146, then save it. If you get an error when trying to save, add a } beneath what you pasted and it should work.

**Comment by EpicGazel** [comment]
Since An0 is Mia, I'm going to be maintaining a fork in the meantime. Not a perfect 1-to-1 so check the README.
https://github.com/EpicGazel/DiscordFreeEmojis

**Comment by Dinoslav** [comment]
> Since An0 is Mia, I'm going to be maintaining a fork in the meantime. Not a perfect 1-to-1 so check the README. https://github.com/EpicGazel/DiscordFreeEmojis

Please, where exactly should i put the "?size=64" in your version?

**Comment by IruzzArcana** [comment]
> > Since An0 is Mia, I'm going to be maintaining a fork in the meantime. Not a perfect 1-to-1 so check the README. https://github.com/EpicGazel/DiscordFreeEmojis
> 
> Please, where exactly should i put the "?size=64" in your version?

Line 146.
```const emojiUrl = `https://cdn.discordapp.com/emojis/${emoji.id}.${emoji.animated ? "gif" : "webp"}?size=64`;```

**Comment by Dinoslav** [comment]
> > > Since An0 is Mia, I'm going to be maintaining a fork in the meantime. Not a perfect 1-to-1 so check the README. https://github.com/EpicGazel/DiscordFreeEmojis
> > 
> > 
> > Please, where exactly should i put the "?size=64" in your version?
> 
> Line 146. `` const emojiUrl = `https://cdn.discordapp.com/emojis/${emoji.id}.${emoji.animated ? "gif" : "webp"}?size=64`; ``

Thanks!

**Comment by PhoebeCheng9911** [comment]
I tried this solution, but I cannot press enter to send the message containing emojis anymore?

**Comment by EpicGazel** [comment]
> I tried this solution, but I cannot press enter to send the message containing emojis anymore?

A fix you can download:
https://github.com/EpicGazel/DiscordFreeEmojis/blob/master/DiscordFreeEmojis64px.plugin.js

**Comment by tic1028** [comment]
Thanks! Will try

From: EpicGazel ***@***.***>
Reply-To: An00nymushun/DiscordFreeEmojis ***@***.***>
Date: Thursday, May 2, 2024 at 10:10 PM
To: An00nymushun/DiscordFreeEmojis ***@***.***>
Cc: Phoebe ***@***.***>, Comment ***@***.***>
Subject: Re: [An00nymushun/DiscordFreeEmojis] [Discord Breaking Change] Can't send emojis (Issue #86)


I tried this solution, but I cannot press enter to send the message containing emojis anymore?

A fix you can download:
https://github.com/EpicGazel/DiscordFreeEmojis/blob/master/DiscordFreeEmojis64px.plugin.js

**Comment by DanzoGit** [comment]
Bro, thanks for doing this. I use this plugin all the time. 💖

**Comment by Outwardwet** [comment]
I changed the plugin to the one given here but I still can't use emojis. It puts my emoji in the message bar but when I press enter it doesn't send

**Comment by EpicGazel** [comment]
> I changed the plugin to the one given here but I still can't use emojis. It puts my emoji in the message bar but when I press enter it doesn't send

Delete the old one from the plugins folder. Enable the new one in your BetterDiscord settings.

I'm going to stop checking in here. If you have issues related to the fork, post them over there.
