### ISSUE TITLE
Emote never sends just grey out and stalls

### ISSUE THREAD

**Issue by Hackatoan** [An00nymushun/DiscordFreeEmojis#87]
**Describe the bug**
Emote never sends just grey out and stalls. 
**To Reproduce**
sent emoji with plugin enabled on betterdb
**Expected behavior**
emoji sends as link. 
**Additional context**
i assume the repo is abandoned but i see some active support in the issues so i dont know if there is a fix for this.

**Comment by Hackatoan** [comment]
read the issue before this and it fixes the issue. 

replace replaceemoji function with 

function replaceEmoji(parseResult, emoji) {
        const emojiUrl = `https://cdn.discordapp.com/emojis/${emoji.id}.${emoji.animated ? "gif" : "webp"}`;
        parseResult.content = parseResult.content.replace(`<${emoji.animated ? "a" : ""}:${emoji.originalName || emoji.name}:${emoji.id}>`,emojiUrl);
    }
    
[   i also made a quick fork with the fix added. ](https://github.com/Hackatoan/DiscordFreeEmojis/tree/master)

**Comment by Thebomb32** [comment]
Hey I used your forked version. Is there anyway to make the emojis smaller? They're massive lol
